# Generated by Django 5.0.7 on 2024-07-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0002_alter_userresume_resumeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresume',
            old_name='email',
            new_name='userEmail',
        ),
        migrations.RenameField(
            model_name='userresume',
            old_name='username',
            new_name='userName',
        ),
        migrations.AlterField(
            model_name='userresume',
            name='resumeId',
            field=models.UUIDField(),
        ),
    ]
