# Generated by Django 5.0.7 on 2024-07-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0004_userresume_address_userresume_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='summery',
            field=models.TextField(blank=True, null=True),
        ),
    ]
