# Generated by Django 5.0.7 on 2024-07-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0005_userresume_summery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresume',
            old_name='summery',
            new_name='summary',
        ),
    ]
