# Generated by Django 5.0.7 on 2024-08-19 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0006_rename_summery_userresume_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('workSummary', models.TextField(blank=True, null=True)),
                ('resumeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_resume.userresume')),
            ],
        ),
    ]
