# Generated by Django 5.0.7 on 2024-08-20 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0007_userexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityName', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('resumeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_resume.userresume')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('resumeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_resume.userresume')),
            ],
        ),
    ]
