# Generated by Django 5.0.7 on 2024-08-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_resume', '0008_usereducation_userskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresume',
            name='themeColor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
